In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df =pd.read_csv("7 churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.shape

(7043, 21)

# Data Preprocessing

In [4]:
#will check the null values are present or not 
df.isnull().sum() #0 null values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# feature engineering
we will keep only the important column that we need

In [5]:
col =['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges','Churn']
df =df[col]

In [6]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,Month-to-month,29.85,No
1,Male,0,No,No,34,Yes,No,One year,1889.5,No
2,Male,0,No,No,2,Yes,No,Month-to-month,108.15,Yes
3,Male,0,No,No,45,No,No phone service,One year,1840.75,No
4,Female,0,No,No,2,Yes,No,Month-to-month,151.65,Yes

# Data encoding
as here for the column that contains yes/no value or the columns that have only 2 classes we will use binary encoding 

[gender, Partner, Dependents,PhoneService,multipleLines,contract, Churn ]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le =LabelEncoder()

In [9]:
#here we will encode all the column that has 2 classes or categories for that we will use loop
categorical_col =['gender','Partner','Dependents','PhoneService','MultipleLines','Contract','Churn']
for  col in categorical_col:
    df[col] = le.fit_transform(df[col])

In [10]:
#to do the same manually we can do it like this
''' binary_columns =['Partner','Dependents','PhoneService','Churn'] #this includes column 
with binary values like yes/no
df[binary_columns] =df[binary_columns].replace({'Yes':0,'No': 1})

#to encode columns like gender or other that has only 2 categorical values
df['gender'] =df['gender'].replace({'Male':0,'Female':1})
'''
#in this way we can encode the values manually

" binary_columns =['Partner','Dependents','PhoneService','Churn'] #this includes column \nwith binary values like yes/no\ndf[binary_columns] =df[binary_columns].replace({'Yes':0,'No': 1})\n\n#to encode columns like gender or other that has only 2 categorical values\ndf['gender'] =df['gender'].replace({'Male':0,'Female':1})\n"

# Train test split 
now the data has no null values and the dataset columns has been encoded now the data is ready for splitting

In [11]:
X =df.drop('Churn',axis =1) #split  dataset in to features (x) and target (y)
y =df['Churn']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state =42)
#splitting data into training and test set

In [14]:
X_train.info() #all values are int except the Total charges column
#total charges colu has data type obj means the numbers stored in it is in strings

<class 'pandas.core.frame.DataFrame'>
Index: 5634 entries, 2142 to 860
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         5634 non-null   int64
 1   SeniorCitizen  5634 non-null   int64
 2   Partner        5634 non-null   int64
 3   Dependents     5634 non-null   int64
 4   tenure         5634 non-null   int64
 5   PhoneService   5634 non-null   int64
 6   MultipleLines  5634 non-null   int64
 7   Contract       5634 non-null   int64
 8   TotalCharges   5634 non-null   object
dtypes: int64(8), object(1)
memory usage: 440.2+ KB

In [15]:
#convert 'TotalCharges' column to float and handle errors ='coerce' to replace non numeric 
#values with Nan
#we apply on both test and train cause 20% data is in test
X_train['TotalCharges'] =pd.to_numeric(X_train['TotalCharges'], errors= 'coerce')
#pd.to_numeric--> will convert the obj/string datatype to number
X_test['TotalCharges'] =pd.to_numeric(X_test['TotalCharges'],errors ='coerce')

#errors =coerce --> replace  the invalid or non numeric value to NaN
'''suppose col given
323
234
aff
234
after pd.to_numeric(col,errors = 'coerce')

col we get 
323
234
NaN
234'''

"suppose col given\n323\n234\naff\n234\nafter pd.to_numeric(col,errors = 'coerce')\n\ncol we get \n323\n234\nNaN\n234"

In [16]:
X_train.isnull().sum() #now it has 10 null values or NaN values

gender            0
SeniorCitizen     0
Partner           0
Dependents        0
tenure            0
PhoneService      0
MultipleLines     0
Contract          0
TotalCharges     10
dtype: int64

In [17]:
#Replacing or filling the missing values in 'TotalCharges' column with the mean of the column
X_train['TotalCharges']= X_train['TotalCharges'].fillna(X_train['TotalCharges'].mean()) #here it will make change in org DF
#this is recommended approach
X_test['TotalCharges']= X_test['TotalCharges'].fillna(X_test['TotalCharges'].mean())
#fillna(value) =find all NaN value and replace them with value(value can be mean median mode)
#here now the dtype of the colu is changed to float

# Standardize features (optionaal but often beneficial for logistic regression)

In [18]:
#we use it to avoid model domination towards large value 
# 2types are there-> domination of largern value in column and within column
from sklearn.preprocessing import StandardScaler

In [19]:
ss =StandardScaler() #load the model

In [20]:
X_train =ss.fit_transform(X_train)
X_test =ss.transform(X_test)

In [21]:
X_train #now it is a numpy array before it was diff value with diff column
#here the value is standardised

array([[-1.02516569, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.42210502],
       [-1.02516569, -0.4377492 , -0.96957859, ...,  1.10833901,
         1.5775905 ,  1.25536015],
       [ 0.97545208, -0.4377492 ,  1.03137591, ...,  0.05390099,
        -0.83177379, -1.00299144],
       ...,
       [ 0.97545208, -0.4377492 ,  1.03137591, ..., -1.00053704,
        -0.83177379, -0.87799925],
       [ 0.97545208,  2.28441306, -0.96957859, ...,  1.10833901,
        -0.83177379, -0.48254445],
       [ 0.97545208, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.81110232]])

# Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
mod = LogisticRegression()

In [24]:
mod.fit(X_train,y_train)
y_pred =mod.predict(X_test)

In [25]:
y_pred

array([1, 0, 0, ..., 0, 0, 1])

# Accuracy Score

In [26]:
from sklearn.metrics import accuracy_score
round(accuracy_score(y_test,y_pred),2) #round--> used to round of the decimal values
#give accuracy score between the result and predicted output

0.78

# saving the model

In [27]:
import pickle 
pickle.dump(mod,open('7_logistic_model.pkl','wb'))

# classification system

In [39]:
def predictive(gender,Seniorcitizen,Partner,Dependents,tenure,Phoneservice,multiline,contract,totalcharge):
    #passing the param value to the required columns of dataset in form column:value
    data ={
        'gender':[gender],
        'SeniorCitizen':[Seniorcitizen],
        'Partner':[Partner],
        'Dependents':[Dependents],
        'tenure':[tenure],
        'PhoneService':[Phoneservice],
        'MultipleLines':[multiline],
        'Contract':[contract],
        'TotalCharges':[totalcharge]
    }
    df1 =pd.DataFrame(data) #converting the data that we pass into dataframe

    #now we will apply all those operation that we did earlier on this dataframe
    categorical_columns =['gender','SeniorCitizen',	'Partner','Dependents',	'tenure','PhoneService','MultipleLines','Contract','TotalCharges']
    for col in categorical_columns:
        df1[col] = le.fit_transform(df1[col]) #label encoding the columns

    df1 =ss.fit_transform(df1) #standardized the values
    result =mod.predict(df1).reshape(1,-1) #after prediction we want the
    return result[0]

In [40]:
#first we will create some variable and pass value of first row
gender ="Female"
Seniorcitizen ="No"
Partner="Yes"
Dependents ="No"
tenure =1
Phoneservice= "No"
multiline ="No phone service"
contract ="Month-to-month"
totalcharge =29.85
#here calling the funct and passing the value for prediction
result =predictive(gender,Seniorcitizen,Partner,Dependents,tenure,Phoneservice,multiline,contract,totalcharge)
if result ==0:
    print("Not churn")
else :
    print("churn")

Not churn

now we will make the web app using streamlit for this model